### ISSUE TITLE
Update eqtl pipeline outputs for browser

### ISSUE THREAD

**Issue by daniaki** [populationgenomics/tob-wgs#97]
# Pipeline output specification

This issue outlines preferred data formats of the analysis pipeline's output.

## Associations
Updates to the columns currently output by the eqtl pipeline.

| Name              | Format                                            | 
| ----------------- | ------------------------------------------------- |
| chrom             | string without 'chr'                              |
| association_id    | chrom:bp:a1:a2:gene_id:cell_type_id:round         |
| cell_type_id      | string                                            |
| cell_type_name    | long form description of cell type (if available) |
| variant_id        | chrom:bp:a2                                       |
| snp_id            | chrom:bp:a1:a2                                    |
| locus             | chrom:bp                                          |
| beta              | number                                            |
| functional_annotation | string from VEP               |
| is_esnp | boolean indicating if eQTL was used to condition the next round

Example:

| association_id | cell_type_id | cell_type_name | chrom | variant_id | snp_id | beta | functional_annotation |
| -------------- | ------------ | -------------- | ----- | ---------- | ------ | ---- | --------------- |
| 6:49458097:A:G:ENSG00000031691:bmem:1 | bmem | Memory B Cell | 6 | 6:49458097:G | 6:49458097:A:G | 0.7 | missense_variant |

The field `id` should be renamed to `association_id` and `snpid` renamed to `snp_id` due to the data format expected by the web UI.

Outputs files in the form `chr1.tsv.gz` or `chr1.parquet` where each file combines results from all cell types and conditioning rounds. If saving as a parquet file, the file should be indexed on `global_bp` with a step size of 2 megabases (MB).

## Gene expression distribution (logCPM)
A table mapping gene identifier and cell type id to a data structure summarising gene expression information from samples grouped by cell type id.

Example:

| gene_id | gene_symbol | cell_type_id | data |
| ------- | ----------- | ------------ | ---- |
| ENSG00000134202 | GSTM3 | bmem | \<structure> |

The `data` field has the dictionary-like form:

```
{
    bin_counts: number[],
    bin_edges: number[],
    n_samples: number,
    min: number,
    max: number,
    mean: number,
    median: number,
    q1: number,
    q3: number,
    iqr: number,
    iqr_min: number, // q1 - 1.5 * (q3 - q1)
    iqr_max: number, // q3 + 1.5 * (q3 - q1)
}
```

Outputs a single file named `gene_expression.parquet`.

## Association effect on gene expression (logCPM)
A table mapping eQTLs to a data structure summarising gene expression information. Samples are grouped based on genotype (0 - hom ref, 1 - het alt, 2 - hom alt) and cell type id. Gene expression summary information is then computed for each grouping.

Example:

| snp_id | global_bp | gene_id | gene_symbol | cell_type_id | genotype | data |
| ------ | --------- | ------- | ----------- | ------------ | -------- | ---- |
| 1:108735360:G:C | 108735360 | ENSG00000134202 | GSTM3 | bmem | 0 | \<structure> |
| 1:108735360:G:C | 108735360 | ENSG00000134202 | GSTM3 | bmem | 1 | \<structure> |
| 1:108735360:G:C | 108735360 | ENSG00000134202 | GSTM3 | bmem | 2 | \<structure> |

The `genotype` field indicates the number of `alt (a2)` alleles in the sample. The field `global_bp` is required to index the table to reduce query costs while increasing query speed. The `snp_id` field should match that in the association table output. The `data` field has the dictionary-like form (same as above):

```
{
    bin_counts: number[],
    bin_edges: number[],
    n_samples: number,
    min: number,
    max: number,
    mean: number,
    median: number,
    q1: number,
    q3: number,
    iqr: number,
    iqr_min: number, // q1 - 1.5 * (q3 - q1)
    iqr_max: number, // q3 + 1.5 * (q3 - q1)
}
```

Outputs a single file named `eqtl_effect.parquet` indexed on `global_bp` with a step size of 2 megabases (MB). This table will be very large on the full data set, so you could first try computing only for associations with an `FDR < 0.05`

## LD information
A table mapping an locus identifier to a structure of loci in LD within **1MB(?)** flank either side.

Example:

| locus | global_bp | data |
| ----- | --------- | ---- |
| 1:108735360 | 108735360 | \<structure> | 

The field `global_bp` is required to index the table to reduce query costs while increasing query speed. The `data` field has the dictionary-like form mapping a locus to a dictionary keyed by locus identifier where values are LD scores:

```
{
   1:108635360: 0.1,
   ...,
   1:108735360: 1.0,
   1:108735361: 0.9,
   1:108735362: 0.1,
   ... 
   1:109735360: 0.5,
}
```

Outputs a single file named `ld.parquet` indexed on `global_bp` with a step size of 2 megabases (or double the size flank used to compute LD)

## Cell type metadata
A table with cell type details:

Example:

| cell_type_id | cell_type_name | description |
| ------- | ----------- | ------------ |
| bmem | Memory B Cell | TCL1A- FCER2- B cell |

Outputs a single file named `cell_types.tsv`.

# Tasks
- [x] Association file update
- [x] Gene expression stats
- [x] Association effect stats
- [ ] LD information
- [x] Cell type metadata
